
name: bububao
on:
  workflow_dispatch:
  schedule:
     - cron: '0,30 0-23 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        BBB_bububaoTOKEN: ${{ secrets.BBB_bububaoTOKEN }}
        BBB_CASH: ${{ secrets.BBB_CASH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【bububao】'
        if: env.BBB_bububaoTOKEN
        run: |
          node Task/bububao.js
        env:
          BBB_bububaoTOKEN: ${{ secrets.BBB_bububaoTOKEN }}
          BBB_CASH: ${{ secrets.BBB_CASH }}
